### ISSUE TITLE
Promethean Undies

### ISSUE THREAD

**Issue by Doctor-Derp** [CarbonLilly/LillyStation12#7]
#### Description of issue
Prometheans cannot wear underwear or socks.

#### Difference between expected and actual behavior
Why can't my Jellies wear undies ;-;

#### Steps to reproduce
Try to change underwear/socks in the Character Creator as a Promethean.

#### Specific information for locating
N/A

#### Length of time in which bug has been known to occur
Since the dawn of Prometheans

#### Client version, Server revision & Game ID
512
5678d6df4182bd832ac6176b93b096366b9dc53d - 2ac6176b93b096366b9dc53d -
b4J-a0zO

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by CarbonLilly** [comment]
Issue should be fixed in latest commit! ^^
