### ISSUE TITLE
Voting.

### ISSUE THREAD

**Issue by Doctor-Derp** [CarbonLilly/LillyStation12#9]
#### Description of issue
Less of an issue and more of a suggestion, people should be able to call restart/crewtransfer votes and such. Some times the round gets messed up so badly, you can't do these things In Character.

#### Difference between expected and actual behavior
You should be able to call these votes, but you can't.

#### Steps to reproduce
Open voting panel as non-admin and try to vote.

#### Specific information for locating
type, "vote"

#### Length of time in which bug has been known to occur
Since start of server.

#### Client version, Server revision & Game ID
N/A

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by CarbonLilly** [comment]
Not a coding problem. Code works as intended. I'm just too dumb to sort out how to enable it. Might have an idea though. At any rate, OFF GITHUB WITH THOU
